name: Build Hook Docs

on:
 push:
   branches:
    - main

jobs:
  hookdocs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version-file: '.nvmrc'
    - name: npm install, and build docs
      run: |
        npm install
        npm run build:docs
    - name: Deploy to GH Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        publish_dir: './docs'
        github_token: ${{ secrets.GITHUB_TOKEN }}